name: dask-mini-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - dask=2021.11.2
  # JupyterLab extensions
  - jupyterlab>=3
  - dask-labextension=5.1.0
  - ipywidgets=7.6.5
  - graphviz=2.49.0
  - python-graphviz=0.17
  - scikit-learn=1.0.1
  - dask-ml=2021.11.16 
  - coiled=0.0.56