name: dask-mini-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - dask=2021.08.1
  # JupyterLab extensions
  - jupyterlab>=3
  - dask-labextension=5.1.0
  - ipywidgets=7.6.5
  - graphviz=2.49.0
  - python-graphviz=0.17
  - scikit-learn=0.24.2
  - dask-ml=1.9
  - coiled